### ISSUE TITLE
メソッド引数におけるデータとソースコードとのマッチング

### ISSUE THREAD

**Issue by tetsuyakanda** [k-shimari/nod4j#166]
Defects4J Lang10b のトレースを処理して表示した結果、org/apache/commons/lang3/time/FastDateParser.java の 464行目
`private static int copy(KeyValue[] fieldKeyValues, int offset, String[] values) {`    
の部分が
KeyValue[] 、int、String[] のところ
String、StringBuilder、Strng の値が表示される

**Comment by k-shimari** [comment]
Merge this update.
